language: cpp
sudo: false # only for faster builds
script:
  - g++ main.cpp -o main
  - ./main
  - gcov main.cpp

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1d61c72a-7625-48c4-a52e-573154e93865
